---
- name: RHEL Patching
  hosts: linux

  tasks:
    - name: List available updates (all)
      yum:
        list: available
      register: update_list
      when: security_patch == "No"
      
    - name: List available updates (security only)
      yum:
        list: available
        security: yes
      register: update_list
      when: security_patch == "Yes"
      
    - name: show list
      debug:
        msg: "{{ update_list|list }}"
