---
- name: RHEL Patching
  hosts: linux

  tasks:
    - name: List available updates (all)
      shell: yum check-updates
      register: update_list
      when: security_patch == "No"
      
    - name: List available updates (security only)
      shell: yum check-updates --security
      register: update_list
      when: security_patch == "Yes"
      
    - name: show list
      debug:
        msg: "{{ update_list|list }}"
