---
- name: RHEL Patching
  hosts: linux

  tasks:
    - name: List available updates (all)
      shell: yum check-updates
      register: update_list_all
      failed_when: update_list_all.rc == 100
      when: security_patch == "No"
      
    - name: List available updates (security only)
      shell: yum check-updates --security
      register: update_list_sec
      failed_when: update_list_sec.rc == 100
      when: security_patch == "Yes"
