---
- name: Run Chef Inspec on Windows
  hosts: windows_target
  
  tasks:
    - name: execute Inspec command
      win_shell: $(inspec exec https://github.com/dev-sec/windows-baseline) >> C:\Users\weihow.owi\windows_scan.txt
      ignore_errors: yes
      
    - name: read the file
      win_shell: cat .\windows.txt
      ignore_errors: yes
      register: scan_results
      
    - name: show results
      debug:
        msg: "{{ scan_results.stdout_lines|list }}" 

#   - name: show results
#      debug:
#        var: scan_results 
